### ISSUE TITLE
Segmentation fault when trying to run perli

### ISSUE THREAD

**Issue by papaiatis** [mklement0/perli#1] opened 2017-12-15 14:04 UTC
I'm on Ubuntu 16.04.3 LTS with Perl 5.22.1 x86_64-linux-gnu-thread-multi.
I downloaded the perli script and copied it to /usr/bin/, added executable flag.
Also installed rlwrap.
When trying to run `perl` I get this: `Segmentation fault (core dumped)`. `dmesg` shows: `21783.622887] perl[12937]: segfault at 5 ip 00007f01db8c59e7 sp 00007ffe26676330 error 4 in Util.so[7f01db8bd000+b000]`

Any idea how to fix it?

Update: it works on my Gentoo installation though

**Comment by mklement0** [comment] 2017-12-16 04:31
I don't have such an environment handy for testing, unfortunately.

`perli` aside, can you run _any_ Perl scripts in this environment?

**Comment by mklement0** [comment] 2017-12-17 04:39
I just tried in the same environment (Ubuntu 16.04.3 LTS, v5.22.1, built for x86_64-linux-gnu-thread-multi), and I don't see the symptom.

Given that you're saying that it happens when you run `perl` rather than `perli`, I'm assuming the problem is unrelated to `perli`, so I'll close this, but we can revisit if you do find evidence that `perli` is at fault.

**Closed by mklement0** 2017-12-17 04:39 UTC

**Comment by papaiatis** [comment] 2017-12-17 06:29
Sorry, it was a typo. Of course I meant `perli`, otherwise I wouldn't have reported the issue here.

**Comment by mklement0** [comment] 2017-12-17 12:40
I see - so back to my original question (and more): 

* Can you run _any_ Perl command in your environment, or ist it _just_ `perli` that produces the symptom?

* If you run something as simple as `perli --version`, do you see the symptom?

* What does `file "$(readlink -f "$(which perli)")"` report? It should be: "... a /usr/bin/env perl script, ASCII text executable ..."

* If you install via `npm`, do you see the same symptom?

**Comment by mklement0** [comment] 2017-12-17 12:58
Sorry about asking about the generic ability to run Perl again (since removed) - when I was notified by email, your edit on that topic hadn't been made yet.

How exactly did you download the `perli` source-code file?

**Comment by papaiatis** [comment] 2017-12-18 09:02
`perli --version` gives me the same Segmentation fault error.

`file "$(readlink -f "$(which perli)")"` gives me `/usr/bin/perli: a /usr/bin/env perl script, ASCII text executable`

I installed it via `npm`, but still I got the same error.

I downloaded the script from Github by copy & paste.

**Comment by mklement0** [comment] 2017-12-18 11:58
That's mysterious. And it happens whether or not you have `rlwrap` installed?

Do you happen to have another VM / machine with the same setup where the symptom doesn't surface?

Honestly, at this point I wouldn't know what to look for, given that I can't reproduce it here.

**Comment by papaiatis** [comment] 2017-12-18 12:12
At first I didn't have `rlwrap` installed. Then I installed it in hope for solving the problem, but that didn't help either.
I tried it in two different ubuntu docker containers, both were working fine. 
I also tried it at another colleague's machine, and it's working at him. 
So my machine's gonna be faulty in some way. Not sure how to resolve though.

**Comment by papaiatis** [comment] 2017-12-18 12:15
I tried debugging it, got some call stack:
```

perl -d /usr/bin/perli --version

Loading DB routines from perl5db.pl version 1.49
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

Signal SEGV at /home/atis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/List/Util.pm line 23.
	require List/Util.pm called at /home/atis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Scalar/Util.pm line 23
	require Scalar/Util.pm called at /usr/share/perl/5.22/File/Temp.pm line 17
	File::Temp::BEGIN() called at /home/atis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/List/Util.pm line 0
	eval {...} called at /home/atis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/List/Util.pm line 0
	require File/Temp.pm called at /usr/bin/perli line 5
	main::BEGIN() called at /home/atis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/List/Util.pm line 0
	eval {...} called at /home/atis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/List/Util.pm line 0
Aborted (core dumped)

```

Let me try to reinstall `List::Util`

**Comment by mklement0** [comment] 2017-12-18 15:21
Cool, thanks for letting me know.
